# Generated by Django 3.0.3 on 2023-05-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='users_mane',
            new_name='users_name',
        ),
    ]
